config/routes.rb
Rails.application.routes.draw do
  get 'favorites/update'
  resources :posters
  devise_for :users
  root 'home#index'
 get 'login', to: 'user#new'
 post 'login', to: 'user#create'
 delete 'logout', to: 'user#destroy'
 resources :likes, only: [:create, :destroy]
 resources :posts do
  resources :comments, only: [:create, :destroy]
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: :post_id }
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true, length: { minimum: 6, maximum: 100 }
    validates :description, presence: true, length: { minimum: 3, maximum: 300 }
belongs_to :user
has_many :comments, dependent: :destroy 
has_many :likes
end

app/models/user.rb
class User < ApplicationRecord
  
    validates :username, presence: true, length: { minimum: 3, maximum: 15 },
    uniqueness: { case_sensitive: false }
    has_many :posts
    has_many :favorites
    has_secure_password
    has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :favorite_text, :logged_in?
  
  def favorite_text
    return @favorite_exists? "UnFavorite" : "Favorite"
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
      @comment = @post.comments.create(params[:comment].permit(:name, :comment))
    redirect_to post_path(@post)    
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def update
    favorite = Favorite.where(post: Post.find(params[:post]), user: current_user)
    if favorite == []
      Favorite.create(post: Post.find(params[:post]), user: current_user)
      @favorite_exists = true
    else
      favorite.destroy_all
      @favorite_exists = false
    end
    respond_to do |format|
      format.html {}
      format.js {}
    end
  end
  def show
    @favourite_exists = Favorite.where(post: @post, user: current_user) == [] ? false : true
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @like = current_user.likes.new(like_params)
        if !@like.save
            flash[:notice] = @like.errors.full_messages.to_sentence
        end
        redirect_to @like.post
    end

    def destroy
        @like = current_user.likes.find(params[:id])
        post = @like.post
        @like.destroy
        redirect_to post
    end

    private

    def like_params
        params.require(:like).permit(:post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    #before_action :authenticate_user!, except: [:index]  

    def index
        @posts = Post.all
    end

    def show
        @post = Post.find(params[:id])
        @favorite_exists = Favorite.where(post: @post, user: current_user) == [] ? false : true
    end
    
    def new
        @post = Post.new
    end

    def edit
        @post = Post.find(params[:id])
    end

    def create
    @post = Post.new(params.require(:post).permit(:title, :description))
    @post.user = User.first
    if @post.save
        flash[:notice] = "Post was created successfully."
        redirect_to @post
      else
        render 'new'
      end
    end

    def update
        @post = Post.find(params[:id])
        if @post.update(params.require(:post).permit(:title, :description))
          flash[:notice] = "Post was updated successfully."
          redirect_to @post
        else
          render 'edit'
        end
    end
    
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
  end

  def create
   user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to login_path
    else
      flash.now[:error] = "There was something wrong with your login information"
     render 'new'
    end
  end  

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have successfully logged out"
    redirect_to login_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      end
    
      def logged_in?
        !!current_user
      end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/_comment.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= comment.name %>:</strong>
          <%= comment.comment %>
        </p>
      </div>
    </div>
     <%= link_to 'Delete', [comment.post, comment],
                  method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %>
  </article>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build], local: true) do |f| %>
  <p>
  <%= f.label :name %><br>
  <%= f. text_field :name %>
  </p>
  <p>
  <%= f.label :comment %><br>
  <%= f. text_area :comment %>
  </p>
  <p>
  <%= f.submit %>
  <p>
  <% end %>

app/views/favorites/index.html.erb
<h1> Your Favorite Posts</h1>
<% current_user.favorites.each do |favorite| %>
You favorited this post: <%= link_to favorite.post.title,favorite.post %>
<br>
<% end %>

app/views/favorites/update.js.erb
$('#favorite_link').text("<%= favorite_text %>");

app/views/home/index.html.erb
<div class="ui placeholder segment">
  <div class="ui two column very relaxed stackable grid">
    <div class="column">
      <%= form_for(:session, html: {class: "ui form", role: "form"}, url: login_path) do |f| %>
        <div class="field">
          <%= f.label :username, "Username" %>
          <div class="ui left icon input">
            <%= f.text_field :username, placeholder: "Username" %>
            <i class="user icon"></i>
          </div>
        </div>
        <div class="field">
          <%= f.label :password, "Password" %>
          <div class="ui left icon input">
            <%= f.password_field :password, placeholder: "Password" %>
            <i class="lock icon"></i>
          </div>
        </div>
        <%= f.button "Login", class: "ui orange submit button" %>
      <% end %>
      
    </div>
    <div class="middle aligned column">
      <div class="ui big orange disabled button">
        <i class="signup icon"></i>
        Sign Up
      </div>
    </div>
  </div>
  <div class="ui vertical divider">
    Or
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
    <div class="ui <%= message_type %> message transition">
      <i class="close icon"></i>
      <div class="header">
        <%= message_content %>
      </div>
    </div>
  <% end %>

app/views/layouts/_navigation.html.erb
<a class="item">
Home
</a>
<div class="right menu">
    <div class="ui simple dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
            <a class="item">Favourites</a>
           
            <a class="item">Logout</a>
            
        </div>
    </div>
    
    
        <div class="item">
            <div class="ui primary button">Sign Up</div>
        </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>users</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="ui small inverted menu">
      <div class="ui container">
        <%= render 'layouts/navigation' %>
      </div>
    </div>
    <div class="ui container">
    <%= render 'layouts/messages' %>
    <% flash.each do |name, msg| %>
      <%= msg %>
    <% end %>  
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="section">
<%= simple_form_for @post do |f| %>
  <div class="field">
    <div class="control">
      <%= f.input :title, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.input :description, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' }  %>
    </div>
  </div>
  <%= f.button :submit, 'Create new post', class: "button is-primary" %>
<% end %>
</div>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<% if @post.errors.any? %>
  
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with(model: @post, local: true) do |f| %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<p>
    <%= link_to 'Return to Post listing', posts_path%>
  </p>

app/views/posts/index.html.erb
<h1>Your Favorite post </h1>

<% current_user.favorites.each do |favorite| %>
You favorited this post: <%= link_to favorite.post.title,
favorite.post %>
<br>
<% end %>

<h1>Post listing page </h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= link_to 'Show', post_path(post) %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Delete', posts_path(post), data: { turbo_confirm: 'Are you sure?', turbo_method: :delete } %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<p>
    <%= link_to 'Create new Post', new_post_path%>
</p>

app/views/posts/new.html.erb
<h1>Create a new post</h1>
 
<% if @post.errors.any? %>
  
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with scope: :post, url: posts_path, local: true do |f| %>
  <p> 
    <%= f.label :title %><br/> 
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br/> 
    <%= f.text_area :description %> 
  </p>
  <p>
    <%= f.submit %> 
  </p>
<% end %>

  <p>
    <%= link_to 'Return to Post listing', posts_path%>
  </p>

app/views/posts/show.html.erb
<h1>Showing Post </h1>



<%= link_to favorite_text, favorites_update_path(post: @post), id:'favorite_lik', remote: true %>



<p><strong>Title: </strong><%= @post.title %></p>
<p><strong>Description: </strong><%= @post.description %></p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Delete', posts_path(@post), data: { turbo_confirm: 'Are you sure?', turbo_method: :delete } %> |
<%= link_to 'Return to Post listing', posts_path%> 
</br>
</br>

<%= @post.likes.count %> Likes
<% like = current_user.likes.find_by(post: @post) %>
<% if like.nil? %>
<form action="/likes" method="post">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<input type="hidden" name="like[post_id]" value="<%= @post.id %>">
<input type="submit" value="👍">
</form>
<% else %>

<form action="<%= like_path(like) %>" method="post">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<input type="hidden" name="_method" value="Delete">
<input type="submit" value="👎">
</form>
<% end %>

</br>


<section class="section comments">
    <div class="container">
        <h2 class="subtitle is-5"><strong><%= @post.comments.count %></strong> Comments</h2>
        <%= render @post.comments %>
        <div class="comment-form">
            <hr />
            <h3 class="subtitle is-3">Leave a reply</h3>
             <%= render 'comments/form' %>
        </div>
    </div>
</section>

app/views/user/new.html.erb
</br>

<%= link_to 'All Posts', posts_path %>

</br>
</br>

<%= link_to 'create new post',  new_post_path %>